
export type IQCategory = 'logical' | 'numerical' | 'verbal' | 'spatial';

export interface IQQuestion {
  id: string;
  category: IQCategory;
  question: string;
  choices: string[];
  choiceSvgs?: string[]; // 追加: 選択肢を画像(SVG)で表示する場合に使用
  answer: string;
  weight: number;
  explanation: string;
  svgData?: string; 
}

/**
 * 200問の高品質知能診断問題バンク
 */
export const IQ_QUESTION_BANK: IQQuestion[] = [
  // --- 1. 論理推理 (Logical: 50問) ---
  { id: "log-1", category: "logical", question: "A, B, C, Dの4人で競争。AはBより早いがCより遅い。DはBより早いがAより遅い。3位は誰？", choices: ["A", "B", "C", "D"], answer: "D", weight: 10, explanation: "順位は C > A > D > B となります。" },
  { id: "log-2", category: "logical", question: "「運動が好きな人は健康である。田中さんは運動が好きではない。」ここから確実に言えることは？", choices: ["田中さんは健康ではない", "田中さんは不健康である", "健康な人は運動が好きである", "何も結論づけられない"], answer: "何も結論づけられない", weight: 12, explanation: "「AならばB」が真でも、その裏「not Aならばnot B」は真とは限りません。" },
  { id: "log-3", category: "logical", question: "正直者の村（常に真実）と嘘つきの村（常に嘘）。村人に「あなたの村はどちらですか？」と聞き、指差した方向が正直者の村である確率は？", choices: ["0%", "50%", "100%", "判定不能"], answer: "100%", weight: 15, explanation: "正直者は自分の方を指し、嘘つきは他人（正直者）の方を指すため、必ず正直者の村を指します。" },
  { id: "log-4", category: "logical", question: "P, Q, Rの3人。P「Qは嘘つきだ」、Q「Rは嘘つきだ」、R「PもQも嘘つきだ」。この中で正直者は？", choices: ["P", "Q", "R", "いない"], answer: "Q", weight: 20, explanation: "Qを真実と仮定すると、Rは嘘、Pも嘘となり、Pの「Qは嘘つき」という発言と矛盾しません。" },
  { id: "log-5", category: "logical", question: "ある暗号で「FIRE」が「GKTH」のとき、「WATER」はどうなる？", choices: ["YCVGT", "YCVHT", "XBUFS", "ZDWGU"], answer: "YCVGT", weight: 12, explanation: "各アルファベットを2つ後ろにずらしています。" },
  { id: "log-6", category: "logical", question: "5つの箱A-E。宝は1つ。ラベルA:宝はここ。ラベルB:Dにはない。ラベルC:AかBにある。ラベルD:ラベルBは嘘。ラベルE:ここにある。1つだけ正しい時、宝は？", choices: ["箱A", "箱B", "箱C", "箱D"], answer: "箱B", weight: 18, explanation: "宝がBにある場合のみ、ラベルBのみが真実となります。" },
  { id: "log-7", category: "logical", question: "「全てのクジラは哺乳類である」の対偶は？", choices: ["哺乳類でないものはクジラではない", "クジラでないものは哺乳類ではない", "哺乳類は全てクジラである", "魚類はクジラでない"], answer: "哺乳類でないものはクジラではない", weight: 10, explanation: "「A→B」の対偶は「not B → not A」です。" },
  { id: "log-8", category: "logical", question: "AはBの兄、CはAの父、DはCの母。BとDの関係は？", choices: ["祖母と孫", "母と子", "叔母と甥", "姉と弟"], answer: "祖母と孫", weight: 8, explanation: "家系図を整理するとDはBの祖母です。" },
  { id: "log-9", category: "logical", question: "月〜金まで掃除当番。AはBの翌日。Cは週の真ん中。Dは月曜ではない。Eは最後。Aは何曜日？", choices: ["火曜日", "水曜日", "木曜日", "金曜日"], answer: "木曜日", weight: 15, explanation: "消去法により木曜日と特定されます。" },
  { id: "log-10", category: "logical", question: "3つのドア。1つは当たり。司会者がハズレを1つ開けた後、選択を変えるべきか？", choices: ["変えた方が確率が高い", "変えても確率は同じ", "変えると確率が下がる", "状況による"], answer: "変えた方が確率が高い", weight: 20, explanation: "モンティ・ホール問題。変えた場合の的中率は2/3になります。" },
  { id: "log-11", category: "logical", question: "暗号「APPLE = 50」「ORANGE = 60」のとき、「BANANA」は？", choices: ["40", "50", "60", "70"], answer: "60", weight: 15, explanation: "文字数×10の規則性です。" },
  { id: "log-12", category: "logical", question: "円卓に6人。Aの向かいはB。CはAの隣ではない。DはCの向かい。EはBの隣。Fはどこ？", choices: ["Aの隣", "Bの隣", "Cの隣", "Dの隣"], answer: "Aの隣", weight: 18, explanation: "配置図を再現するとFはAの隣になります。" },
  { id: "log-13", category: "logical", question: "「天才は努力する。私は努力しない。」結論は？", choices: ["私は天才ではない", "私は凡人である", "努力しない人は天才ではない", "天才は私ではない"], answer: "私は天才ではない", weight: 10, explanation: "対偶「努力しないならば天才ではない」が適用されます。" },
  { id: "log-14", category: "logical", question: "箱の中に赤玉3、白玉2。同時に2個取り出すとき、少なくとも1つ赤である確率は？", choices: ["3/10", "7/10", "9/10", "1/10"], answer: "9/10", weight: 15, explanation: "余事象（両方白：1/10）を1から引きます。" },
  { id: "log-15", category: "logical", question: "「AならばB」と「BならばC」が真のとき、確実に言えるのは？", choices: ["AならばC", "CならばA", "BならばA", "not Aならばnot C"], answer: "AならばC", weight: 10, explanation: "三段論法です。" },
  { id: "log-16", category: "logical", question: "ある暗号で「DOG」が「4-15-7」のとき、「CAT」は？", choices: ["3-1-20", "2-1-19", "3-5-18", "4-2-21"], answer: "3-1-20", weight: 8, explanation: "アルファベットの順番号です。" },
  { id: "log-17", category: "logical", question: "4人でカード。A「Dが1位」B「私が1位」C「Bは嘘つき」D「Aは嘘つき」。1人だけ本当なら、1位は誰？", choices: ["A", "B", "C", "D"], answer: "D", weight: 22, explanation: "Dが本当なら他が嘘になり矛盾しません。" },
  { id: "log-18", category: "logical", question: "昨日の明後日の昨日の今日は？", choices: ["昨日", "今日", "明日", "一昨日"], answer: "明日", weight: 12, explanation: "言葉の時系列を整理すると「明日」です。" },
  { id: "log-19", category: "logical", question: "赤、青、黄の旗。赤が上がれば青も。黄が下がれば赤も下がる。今、黄が上がっている。赤は？", choices: ["上がっている", "下がっている", "わからない", "青と同じ"], answer: "わからない", weight: 12, explanation: "必要条件が満たされていないため不明です。" },
  { id: "log-20", category: "logical", question: "100人のうち英語70人、数学60人。両方好きな最小人数は？", choices: ["10人", "30人", "60人", "70人"], answer: "30人", weight: 15, explanation: "70+60-100 = 30 です。" },
  { id: "log-21", category: "logical", question: "「嘘」と「真」が入れ替わる回路。入力が「真・嘘・真」で最後に反転1回なら？", choices: ["嘘・真・嘘", "真・真・真", "嘘・嘘・嘘", "変化なし"], answer: "嘘・真・嘘", weight: 10, explanation: "各要素が1回ずつ反転します。" },
  { id: "log-22", category: "logical", question: "集合P「素数」、集合Q「奇数」。2はどの部分？", choices: ["Pのみ", "Qのみ", "PかつQ", "どちらでもない"], answer: "Pのみ", weight: 8, explanation: "2は偶数の素数です。" },
  { id: "log-23", category: "logical", question: "暗号「SKY=T L Z」なら「SUN」は？", choices: ["T V O", "R T M", "U V O", "T U M"], answer: "T V O", weight: 10, explanation: "各文字を1つ進めています。" },
  { id: "log-24", category: "logical", question: "「AまたはB」の否定として正しいのは？", choices: ["AかつB", "Aでない、かつBでない", "Aでない、またはBでない", "Bでない"], answer: "Aでない、かつBでない", weight: 12, explanation: "ド・モルガンの法則です。" },
  { id: "log-25", category: "logical", question: "トーナメントで64チーム。優勝決定まで何試合？", choices: ["32", "63", "64", "127"], answer: "63", weight: 10, explanation: "n-1 試合行われます。" },
  { id: "log-26", category: "logical", question: "P->Q, Q->R, R->S。Sでないなら？", choices: ["Pでない", "Qである", "Rである", "何も言えない"], answer: "Pでない", weight: 15, explanation: "対偶の連鎖です。" },
  { id: "log-27", category: "logical", question: "A「Bは嘘」B「Cは嘘」C「Aは嘘」。この中で嘘つきは最大何人？", choices: ["1人", "2人", "3人", "0人"], answer: "2人", weight: 18, explanation: "誰かが真実なら他2人が嘘になります。" },
  { id: "log-28", category: "logical", question: "時計の長針と短針が1日に重なる回数は？", choices: ["22回", "23回", "24回", "12回"], answer: "22回", weight: 20, explanation: "計算上、11回×2 = 22回となります。" },
  { id: "log-29", category: "logical", question: "暗号「RED=7-2-11」なら「BLUE」の最初は？", choices: ["11", "5", "9", "2"], answer: "11", weight: 15, explanation: "文字順+9の規則性です。" },
  { id: "log-30", category: "logical", question: "1,2,3,4のカード。偶数の裏は母音。確認すべきは？(A:2, B:3, C:E, D:K)", choices: ["AとD", "Aのみ", "AとC", "BとD"], answer: "AとD", weight: 25, explanation: "4枚カード問題の論理です。" },
  { id: "log-31", category: "logical", question: "「もし私が王なら、君は家来だ」が偽になるのは？", choices: ["私が王で、君が王の時", "私が王で、君が家来でない時", "私が王でない時", "どちらも王でない時"], answer: "私が王で、君が家来でない時", weight: 15, explanation: "Pが真でQが偽の時のみ偽です。" },
  { id: "log-32", category: "logical", question: "AはBの2倍、BはCの3倍。AはCの何倍？", choices: ["5", "6", "9", "2"], answer: "6", weight: 5, explanation: "2 * 3 = 6 です。" },
  { id: "log-33", category: "logical", question: "集合A{1,2,3}, B{3,4,5}。和集合A∪Bの要素数は？", choices: ["5", "6", "1", "3"], answer: "5", weight: 5, explanation: "重複を除くと 1,2,3,4,5 です。" },
  { id: "log-34", category: "logical", question: "10人が互いに握手すると合計何回？", choices: ["45", "90", "100", "10"], answer: "45", weight: 15, explanation: "10C2 = 45 です。" },
  { id: "log-35", category: "logical", question: "「嘘つきは泥棒の始まり」の逆は？", choices: ["泥棒は嘘つきの始まりだ", "嘘をつかねば泥棒でない", "泥棒でなければ嘘つきでない", "嘘をつくなら泥棒だ"], answer: "泥棒は嘘つきの始まりだ", weight: 10, explanation: "B→A が逆です。" },
  { id: "log-36", category: "logical", question: "昨日の昨日の明後日は？", choices: ["一昨日", "昨日", "今日", "明日"], answer: "今日", weight: 5, explanation: "-1-1+2 = 0 です。" },
  { id: "log-37", category: "logical", question: "暗号「HOT=IPU」なら「COLD」は？", choices: ["DPME", "BNCF", "DPME", "BOMD"], answer: "DPME", weight: 10, explanation: "各文字を1つ進めています。" },
  { id: "log-38", category: "logical", question: "「晴れの日は傘がいらない。今、傘を持っていない。ゆえに今日は晴れだ。」この推論は？", choices: ["正しい", "正しくない（逆）", "正しくない（裏）", "判定不能"], answer: "正しくない（逆）", weight: 15, explanation: "後件肯定の誤謬です。" },
  { id: "log-39", category: "logical", question: "A,B,Cの真ん中はB。C,D,Eの真ん中はD。A,B,C,D,Eの真ん中は？", choices: ["B", "C", "D", "E"], answer: "C", weight: 5, explanation: "順序は A-B-C-D-E です。" },
  { id: "log-40", category: "logical", question: "ある国の法律「20歳未満は酒禁止」。守られているか確認するのに不要な情報は？", choices: ["18歳の人が何を飲んでいるか", "酒を飲んでいる人が何歳か", "お茶を飲んでいる人が何歳か", "25歳の人が何を飲んでいるか"], answer: "お茶を飲んでいる人が何歳か", weight: 20, explanation: "お茶を飲む人は法律に関係しません。" },
  { id: "log-41", category: "logical", question: "「AかつB」の否定は？", choices: ["Aでない、かつBでない", "Aでない、またはBでない", "Aでない", "Bでない"], answer: "Aでない、またはBでない", weight: 12, explanation: "ド・モルガンの法則。" },
  { id: "log-42", category: "logical", question: "P=Q, Q=R, R=S。PはSの何？", choices: ["必要条件", "十分条件", "必要十分条件", "無関係"], answer: "必要十分条件", weight: 15, explanation: "同値関係です。" },
  { id: "log-43", category: "logical", question: "「勉強すれば合格する」。合格しなかった。何が言える？", choices: ["勉強していなかった", "運が悪かった", "問題が難しかった", "何も言えない"], answer: "勉強していなかった", weight: 12, explanation: "対偶が適用されます。" },
  { id: "log-44", category: "logical", question: "ベン図の問題。A⊂B のとき正しいのは？", choices: ["AかつB = A", "AかつB = B", "AまたはB = A", "Aではない = B"], answer: "AかつB = A", weight: 15, explanation: "集合の包含関係の定義です。" },
  { id: "log-45", category: "logical", question: "暗号「1=A, 2=B...」のとき、「8-5-12-16」は？", choices: ["HELP", "HOLD", "HELL", "HARD"], answer: "HELP", weight: 10, explanation: "H=8, E=5, L=12, P=16 です。" },
  { id: "log-46", category: "logical", question: "4人でリレー。Aは1番ではない。Bは最後。CはAの次。Dは？", choices: ["1番", "2番", "3番", "4番"], answer: "1番", weight: 18, explanation: "D(1)-A(2)-C(3)-B(4) となります。" },
  { id: "log-47", category: "logical", question: "「高い薬は効く」が真。確実に言えるのは？", choices: ["効く薬は高い", "安ければ効かない", "効かない薬は高くない", "安い薬は効く"], answer: "効かない薬は高くない", weight: 12, explanation: "対偶のみが真です。" },
  { id: "log-48", category: "logical", question: "ある暗号で「314 = PI」なら「271」は？", choices: ["E", "A", "G", "S"], answer: "E", weight: 25, explanation: "数学定数（π=3.14, e=2.71）に関連。" },
  { id: "log-49", category: "logical", question: "「鳥は空を飛ぶ」の裏は？", choices: ["飛ぶなら鳥だ", "飛ばないなら鳥でない", "鳥でないなら飛ばない", "鳥でも飛ばない"], answer: "鳥でないなら飛ばない", weight: 10, explanation: "「not A → not B」が裏です。" },
  { id: "log-50", category: "logical", question: "A「私は嘘つきだ」。この発言は？", choices: ["正しい", "正しくない", "矛盾している", "判定不能"], answer: "矛盾している", weight: 30, explanation: "自己言及のパラドックスです。" },

  // --- 2. 数値処理 (Numerical: 50問) ---
  { id: "num-1", category: "numerical", question: "1, 3, 6, 10, 15, ? 次は？", choices: ["18", "20", "21", "25"], answer: "21", weight: 5, explanation: "+2, +3, +4, +5, +6 と増えています。" },
  { id: "num-2", category: "numerical", question: "10%の食塩水200gに食塩を何g足せば20%になる？", choices: ["20", "25", "30", "40"], answer: "25", weight: 15, explanation: "方程式 (20+x)/(200+x) = 0.2 より x=25 です。" },
  { id: "num-3", category: "numerical", question: "2, 6, 12, 20, 30, ? 次は？", choices: ["36", "40", "42", "48"], answer: "42", weight: 8, explanation: "1*2, 2*3, 3*4, 4*5, 5*6, 6*7 です。" },
  { id: "num-4", category: "numerical", question: "サイコロ2個。和が7になる確率は？", choices: ["1/6", "1/12", "5/36", "1/18"], answer: "1/6", weight: 10, explanation: "6/36 = 1/6 です。" },
  { id: "num-5", category: "numerical", question: "時速60kmの車が15分間に進む距離は？", choices: ["10km", "15km", "20km", "4km"], answer: "15km", weight: 5, explanation: "60 * (15/60) = 15 です。" },
  { id: "num-6", category: "numerical", question: "1から100まで足すと？", choices: ["5000", "5050", "5100", "5500"], answer: "5050", weight: 10, explanation: "(1+100)*100/2 = 5050 です。" },
  { id: "num-7", category: "numerical", question: "20%引きで買い、500円券使用。3500円払った。定価は？", choices: ["4000", "5000", "5500", "6000"], answer: "5000", weight: 12, explanation: "(x*0.8)-500=3500 より x=5000 です。" },
  { id: "num-8", category: "numerical", question: "0, 1, 1, 2, 3, 5, 8, ? 次は？", choices: ["11", "12", "13", "15"], answer: "13", weight: 8, explanation: "フィボナッチ数列です。" },
  { id: "num-9", category: "numerical", question: "半径3cmの円の面積は？（π使用）", choices: ["3π", "6π", "9π", "12π"], answer: "9π", weight: 5, explanation: "π * 3^2 = 9π です。" },
  { id: "num-10", category: "numerical", question: "5人で10日かかる仕事。2人ですると何日？", choices: ["4", "15", "20", "25"], answer: "25", weight: 12, explanation: "50人日 / 2人 = 25日です。" },
  { id: "num-11", category: "numerical", question: "1, 4, 9, 16, 25, ? 次は？", choices: ["30", "36", "40", "49"], answer: "36", weight: 5, explanation: "n^2 の数列です。" },
  { id: "num-12", category: "numerical", question: "時計が4時。長針と短針の角は？", choices: ["90度", "120度", "150度", "180度"], answer: "120度", weight: 10, explanation: "30度 * 4 = 120度。" },
  { id: "num-13", category: "numerical", question: "√144 は？", choices: ["12", "14", "16", "24"], answer: "12", weight: 5, explanation: "12 * 12 = 144。" },
  { id: "num-14", category: "numerical", question: "3人の平均80点。4人目60点なら平均は？", choices: ["70", "72", "75", "78"], answer: "75", weight: 10, explanation: "(240+60)/4 = 75。" },
  { id: "num-15", category: "numerical", question: "1, 8, 27, 64, ? 次は？", choices: ["100", "125", "150", "216"], answer: "125", weight: 15, explanation: "n^3 の数列。" },
  { id: "num-16", category: "numerical", question: "分速1.2kmは何m/s？", choices: ["10", "20", "60", "120"], answer: "20", weight: 15, explanation: "1200m / 60s = 20。" },
  { id: "num-17", category: "numerical", question: "1, 2, 4, 8, 16, ? 次は？", choices: ["24", "30", "32", "64"], answer: "32", weight: 5, explanation: "2^n の数列。" },
  { id: "num-18", category: "numerical", question: "10, 11, 13, 16, 20, ? 次は？", choices: ["24", "25", "26", "28"], answer: "25", weight: 8, explanation: "+1, +2, +3, +4, +5。" },
  { id: "num-19", category: "numerical", question: "底辺2倍、高さ3倍の三角形の面積は元の何倍？", choices: ["2", "3", "5", "6"], answer: "6", weight: 5, explanation: "2 * 3 = 6 倍。" },
  { id: "num-20", category: "numerical", question: "0.1, 0.01, 0.001, ? 次は？", choices: ["0.0001", "0.0011", "0.00001", "0"], answer: "0.0001", weight: 5, explanation: "1/10倍ずつ。" },
  { id: "num-21", category: "numerical", question: "10進数の10を2進数にすると？", choices: ["1010", "1100", "1001", "1111"], answer: "1010", weight: 15, explanation: "8+2 = 1010。" },
  { id: "num-22", category: "numerical", question: "A:B=2:3, B:C=4:5 のとき A:Cは？", choices: ["2:5", "6:15", "8:15", "10:12"], answer: "8:15", weight: 12, explanation: "最小公倍数で合わせます。" },
  { id: "num-23", category: "numerical", question: "1/2 + 1/4 + 1/8 + ... 無限に足すと？", choices: ["1", "2", "無限", "0.99"], answer: "1", weight: 20, explanation: "無限等比級数の和。" },
  { id: "num-24", category: "numerical", question: "2, 5, 11, 23, ? 次は？", choices: ["35", "45", "47", "49"], answer: "47", weight: 15, explanation: "2x + 1 の規則。" },
  { id: "num-25", category: "numerical", question: "300円の林檎を2割引きで3個買った。合計は？", choices: ["720", "240", "900", "600"], answer: "720", weight: 5, explanation: "240 * 3 = 720。" },
  { id: "num-26", category: "numerical", question: "4, 9, 25, 49, ? 次は？", choices: ["64", "81", "100", "121"], answer: "121", weight: 20, explanation: "素数の2乗の数列。" },
  { id: "num-27", category: "numerical", question: "ある数の3倍から10引くと20。その数は？", choices: ["5", "10", "15", "20"], answer: "10", weight: 5, explanation: "3x - 10 = 20。" },
  { id: "num-28", category: "numerical", question: "正六角形の対角線の数は？", choices: ["6", "9", "12", "15"], answer: "9", weight: 18, explanation: "n(n-3)/2 公式。" },
  { id: "num-29", category: "numerical", question: "1, 2, 6, 24, 120, ? 次は？", choices: ["240", "600", "720", "840"], answer: "720", weight: 15, explanation: "階乗の数列。" },
  { id: "num-30", category: "numerical", question: "コイン3回。すべて表の確率は？", choices: ["1/3", "1/4", "1/6", "1/8"], answer: "1/8", weight: 8, explanation: "(1/2)^3。" },
  { id: "num-31", category: "numerical", question: "1, 10, 100, 1000, ? 次は？", choices: ["1001", "10000", "1111", "2000"], answer: "10000", weight: 3, explanation: "10倍ずつ。" },
  { id: "num-32", category: "numerical", question: "1, 3, 7, 15, 31, ? 次は？", choices: ["60", "62", "63", "65"], answer: "63", weight: 12, explanation: "2^n - 1。" },
  { id: "num-33", category: "numerical", question: "20, 18, 15, 11, ? 次は？", choices: ["10", "8", "6", "4"], answer: "6", weight: 10, explanation: "-2, -3, -4, -5。" },
  { id: "num-34", category: "numerical", question: "1から10まで偶数を足すと？", choices: ["20", "25", "30", "55"], answer: "30", weight: 5, explanation: "2+4+6+8+10。" },
  { id: "num-35", category: "numerical", question: "x+y=10, x-y=2。xは？", choices: ["4", "5", "6", "8"], answer: "6", weight: 8, explanation: "加減法。" },
  { id: "num-36", category: "numerical", question: "1, 4, 13, 40, ? 次は？", choices: ["80", "120", "121", "160"], answer: "121", weight: 20, explanation: "3x + 1 の規則。" },
  { id: "num-37", category: "numerical", question: "立方体の一辺を2倍に。体積は何倍？", choices: ["2", "4", "6", "8"], answer: "8", weight: 10, explanation: "2^3 = 8 倍。" },
  { id: "num-38", category: "numerical", question: "10%引きで1800円。元の価格は？", choices: ["1980", "2000", "2100", "2200"], answer: "2000", weight: 5, explanation: "1800 / 0.9。" },
  { id: "num-39", category: "numerical", question: "12, 23, 34, 45, ? 次は？", choices: ["54", "55", "56", "67"], answer: "56", weight: 10, explanation: "11ずつ増加。" },
  { id: "num-40", category: "numerical", question: "1円, 5円, 10円硬貨各1枚。作れる金額数は？", choices: ["3", "7", "8", "16"], answer: "7", weight: 12, explanation: "2^3 - 1。" },
  { id: "num-41", category: "numerical", question: "√2 の近似値は？", choices: ["1.41", "1.73", "2.23", "3.14"], answer: "1.41", weight: 3, explanation: "一夜一夜に。" },
  { id: "num-42", category: "numerical", question: "三角形の内角の和は？", choices: ["90", "180", "270", "360"], answer: "180", weight: 3, explanation: "基本知識。" },
  { id: "num-43", category: "numerical", question: "10, 7, 4, 1, ? 次は？", choices: ["0", "-1", "-2", "-3"], answer: "-2", weight: 8, explanation: "-3ずつ。" },
  { id: "num-44", category: "numerical", question: "1, 1/2, 1/3, 1/4, ? 次は？", choices: ["1/5", "1/6", "1/8", "0"], answer: "1/5", weight: 3, explanation: "分母+1。" },
  { id: "num-45", category: "numerical", question: "5! は？", choices: ["25", "60", "120", "150"], answer: "120", weight: 10, explanation: "5*4*3*2*1。" },
  { id: "num-46", category: "numerical", question: "黄金比は約？", choices: ["1:1.41", "1:1.61", "1:2", "1:3.14"], answer: "1:1.61", weight: 15, explanation: "(1+√5)/2。" },
  { id: "num-47", category: "numerical", question: "1, 2, 4, 7, 11, ? 次は？", choices: ["15", "16", "17", "18"], answer: "16", weight: 10, explanation: "+1, +2, +3, +4, +5。" },
  { id: "num-48", category: "numerical", question: "x^2 - 5x + 6 = 0 の解は？", choices: ["2,3", "1,6", "-2,-3", "1,5"], answer: "2,3", weight: 15, explanation: "因数分解。" },
  { id: "num-49", category: "numerical", question: "秒速10mは時速何km？", choices: ["3.6", "10", "36", "360"], answer: "36", weight: 12, explanation: "10 * 3600 / 1000。" },
  { id: "num-50", category: "numerical", question: "1, 0, 1, 0, ? 次は？", choices: ["1", "0", "-1", "2"], answer: "1", weight: 3, explanation: "交互。" },

  // --- 3. 言語能力 (Verbal: 50問) ---
  { id: "ver-1", category: "verbal", question: "「饒舌」の対義語は？", choices: ["能弁", "寡黙", "巧言", "多弁"], answer: "寡黙", weight: 7, explanation: "よく喋ることの反対は少ないことです。" },
  { id: "ver-2", category: "verbal", question: "「木：森」の関係と同じペアは？", choices: ["草：花", "星：宇宙", "水：氷", "鳥：羽"], answer: "星：宇宙", weight: 8, explanation: "個体と集合の関係。" },
  { id: "ver-3", category: "verbal", question: "「月下氷人」とは何を指す？", choices: ["冷酷な人", "仲人", "隠居した人", "夜逃げする人"], answer: "仲人", weight: 12, explanation: "縁結びの人です。" },
  { id: "ver-4", category: "verbal", question: "「忖度」の意味は？", choices: ["推し量る", "非難する", "優先する", "法律を守る"], answer: "推し量る", weight: 8, explanation: "他人の心を察すること。" },
  { id: "ver-5", category: "verbal", question: "「破天荒」の本来の意味は？", choices: ["豪快な", "前人未到の", "荒れている", "計画が崩れた"], answer: "前人未到の", weight: 12, explanation: "誰も成し得なかったこと。" },
  { id: "ver-6", category: "verbal", question: "「猫に小判」と同じ意味は？", choices: ["馬の耳に念仏", "犬も歩けば", "虎の威を借る", "泣きっ面に蜂"], answer: "馬の耳に念仏", weight: 10, explanation: "価値が分からない人に与える無駄。" },
  { id: "ver-7", category: "verbal", question: "「邂逅」の意味は？", choices: ["別れ", "再会", "思いがけない出会い", "口論"], answer: "思いがけない出会い", weight: 15, explanation: "偶然の巡り合い。" },
  { id: "ver-8", category: "verbal", question: "「杜撰」の語源に関係するのは？", choices: ["料理", "詩", "建物", "衣服"], answer: "詩", weight: 18, explanation: "杜黙の詩が不規則だったことから。" },
  { id: "ver-9", category: "verbal", question: "「慇懃無礼」とは？", choices: ["丁寧すぎて失礼", "怒って暴れる", "嘘を付く", "無口で怖い"], answer: "丁寧すぎて失礼", weight: 10, explanation: "丁寧さが度を超して逆に見下していること。" },
  { id: "ver-10", category: "verbal", question: "「舎本逐末」に近いのは？", choices: ["本末転倒", "一生懸命", "自業自得", "五里霧中"], answer: "本末転倒", weight: 12, explanation: "大事な根源を捨て末節を追う。" },
  { id: "ver-11", category: "verbal", question: "「カラス」の漢字はどれ？", choices: ["鳥", "梟", "鴉", "鴎"], answer: "鴉", weight: 5, explanation: "ハ（牙）の音を持つ鳥。" },
  { id: "ver-12", category: "verbal", question: "「捲土重来」の意味は？", choices: ["敗者が勢いを取り戻す", "土地を耕す", "繰り返し言う", "重い荷物を運ぶ"], answer: "敗者が勢いを取り戻す", weight: 15, explanation: "一度負けた者が盛り返す。" },
  { id: "ver-13", category: "verbal", question: "「（ ）を濁す」空欄は？", choices: ["目", "口", "言葉", "お茶"], answer: "お茶", weight: 5, explanation: "お茶を濁す＝ごまかす。" },
  { id: "ver-14", category: "verbal", question: "「敷居が高い」の本来の意味は？", choices: ["高級すぎる", "不義理で合わせにくい", "段差が大きい", "値段が高い"], answer: "不義理で合わせにくい", weight: 15, explanation: "申し訳ないことがあり訪ねにくい。" },
  { id: "ver-15", category: "verbal", question: "「情けは人のためならず」の正しい意味は？", choices: ["無用だ", "自分に返ってくる", "人は求めない", "甘くしない"], answer: "自分に返ってくる", weight: 10, explanation: "良いことをすれば自分に返る。" },
  { id: "ver-16", category: "verbal", question: "「姑息」の本来の意味は？", choices: ["卑怯な", "一時しのぎの", "古い考えの", "ケチな"], answer: "一時しのぎの", weight: 15, explanation: "根本解決でないしのぎ。" },
  { id: "ver-17", category: "verbal", question: "「穿った見方」の意味は？", choices: ["ひねくれた", "本質を突いた", "疑り深い", "表面的な"], answer: "本質を突いた", weight: 15, explanation: "鋭く捉えること。" },
  { id: "ver-18", category: "verbal", question: "「琴線に触れる」の意味は？", choices: ["怒らせる", "感動させる", "秘密を暴く", "演奏する"], answer: "感動させる", weight: 10, explanation: "深く心を揺り動かす。" },
  { id: "ver-19", category: "verbal", question: "「（ ）も積もれば山となる」", choices: ["砂", "石", "塵", "埃"], answer: "塵", weight: 5, explanation: "塵も積もれば。" },
  { id: "ver-20", category: "verbal", question: "「鼎談」は何人で話す？", choices: ["2", "3", "4", "大勢"], answer: "3", weight: 12, explanation: "鼎の足が3本から。" },
  { id: "ver-21", category: "verbal", question: "「白眉」の意味は？", choices: ["最も優れたもの", "顔が白い", "年老いた", "恥ずかしい"], answer: "最も優れたもの", weight: 15, explanation: "馬氏五兄弟の故事から。" },
  { id: "ver-22", category: "verbal", question: "「泰然自若」の読みは？", choices: ["たいぜんじじゃく", "たいぜんじわく", "やすぜんじじゃく", "たいねんじじゃく"], answer: "たいぜんじじゃく", weight: 5, explanation: "動じない様子。" },
  { id: "ver-23", category: "verbal", question: "「（ ）の功名」", choices: ["棚", "怪我", "瓢箪", "偶然"], answer: "怪我", weight: 10, explanation: "怪我の功名。" },
  { id: "ver-24", category: "verbal", question: "「馬脚を（ ）」", choices: ["出す", "現す", "見せる", "隠す"], answer: "現す", weight: 8, explanation: "ボロが出る。" },
  { id: "ver-25", category: "verbal", question: "「忸怩たる思い」とは？", choices: ["恥じ入る", "怒り狂う", "誇らしい", "悲しい"], answer: "恥じ入る", weight: 15, explanation: "心から恥ずかしく思う。" },
  { id: "ver-26", category: "verbal", question: "「蛇足」の由来は？", choices: ["蛇に足を描いた", "足があった", "足で踏んだ", "足を食べた"], answer: "蛇に足を描いた", weight: 10, explanation: "余計な付け足し。" },
  { id: "ver-27", category: "verbal", question: "「（ ）を呑む」驚くさまは？", choices: ["水", "息", "声", "唾"], answer: "息", weight: 5, explanation: "息を呑む。" },
  { id: "ver-28", category: "verbal", question: "「（ ）に釘」", choices: ["豆腐", "糠", "壁", "紙"], answer: "糠", weight: 10, explanation: "手応えがない。" },
  { id: "ver-29", category: "verbal", question: "「五月雨式」の読みは？", choices: ["さみだれしき", "ごがつあめしき", "さつきあめしき", "さつきばれしき"], answer: "さみだれしき", weight: 8, explanation: "断続的に続く。" },
  { id: "ver-30", category: "verbal", question: "「折半」とは？", choices: ["半分に分ける", "三等分", "半分捨てる", "合わせる"], answer: "半分に分ける", weight: 5, explanation: "費用などを半分ずつ負担。" },
  { id: "ver-31", category: "verbal", question: "「おためごかし」の意味は？", choices: ["親切を装い利を図る", "料理失敗", "逃げる", "あだで返す"], answer: "親切を装い利を図る", weight: 18, explanation: "相手のためと言いつつ自分中心。" },
  { id: "ver-32", category: "verbal", question: "「（ ）の手も借りたい」", choices: ["犬", "猫", "猿", "子供"], answer: "猫", weight: 3, explanation: "非常に忙しい。" },
  { id: "ver-33", category: "verbal", question: "「目から（ ）」", choices: ["汗", "涙", "火", "鱗"], answer: "鱗", weight: 5, explanation: "急に理解する。" },
  { id: "ver-34", category: "verbal", question: "「推敲」の由来は？", choices: ["押すか叩くか", "書くか消すか", "読むか聞くか", "行くか戻るか"], answer: "押すか叩くか", weight: 15, explanation: "言葉を練る故事。" },
  { id: "ver-35", category: "verbal", question: "「青天の（ ）」", choices: ["雷", "霹靂", "星", "雲"], answer: "霹靂", weight: 12, explanation: "不意の大変なこと。" },
  { id: "ver-36", category: "verbal", question: "「（ ）を洗う」悪い縁を切る。", choices: ["足", "手", "口", "顔"], answer: "足", weight: 8, explanation: "足を洗う。" },
  { id: "ver-37", category: "verbal", question: "「不文律」とは？", choices: ["文字でない法", "暗黙の了解", "間違った規則", "古い法律"], answer: "暗黙の了解", weight: 12, explanation: "明文化されていない決まり。" },
  { id: "ver-38", category: "verbal", question: "「栴檀は双葉より（ ）」", choices: ["馨し", "美し", "強し", "高し"], answer: "馨し", weight: 15, explanation: "大成する人は幼少から優れる。" },
  { id: "ver-39", category: "verbal", question: "「他山の石」の意味は？", choices: ["他人のミスを教材にする", "他人の宝物", "遠くの山", "役に立たないもの"], answer: "他人のミスを教材にする", weight: 15, explanation: "他人の振る舞いから自分を正す。" },
  { id: "ver-40", category: "verbal", question: "「役不足」の正しい使い方は？", choices: ["実力に対して役が軽すぎる", "実力不足で役がこなせない", "役者が足りない", "やる気がない"], answer: "実力に対して役が軽すぎる", weight: 20, explanation: "誤用が多い言葉。" },
  { id: "ver-41", category: "verbal", question: "「（ ）に水」驚くさま。", choices: ["寝耳", "立ち耳", "耳元", "壁"], answer: "寝耳", weight: 5, explanation: "不意の出来事。" },
  { id: "ver-42", category: "verbal", question: "「（ ）の上の空論」", choices: ["山", "机", "雲", "畳"], answer: "机", weight: 5, explanation: "役に立たない理屈。" },
  { id: "ver-43", category: "verbal", question: "「勧善懲悪」の対義的な概念は？", choices: ["弱肉強食", "因果応報", "厚顔無恥", "不徳義"], answer: "弱肉強食", weight: 15, explanation: "正義でなく力のみが支配。" },
  { id: "ver-44", category: "verbal", question: "「（ ）を投げ出す」あきらめる。", choices: ["匙", "箸", "皿", "靴"], answer: "匙", weight: 10, explanation: "医者が匙を置くことから。" },
  { id: "ver-45", category: "verbal", question: "「（ ）を割る」告白する。", choices: ["口", "腹", "壁", "窓"], answer: "口", weight: 10, explanation: "隠していたことを話す。" },
  { id: "ver-46", category: "verbal", question: "「食指が動く」とは？", choices: ["空腹", "食欲なし", "興味がわく", "指が震える"], answer: "興味がわく", weight: 10, explanation: "手に入れたい気持ち。" },
  { id: "ver-47", category: "verbal", question: "「氷山の一角」とは？", choices: ["全体の一部", "冷たいもの", "批判", "北極にあるもの"], answer: "全体の一部", weight: 5, explanation: "表面上のわずかな部分。" },
  { id: "ver-48", category: "verbal", question: "「（ ）を打つ」納得する。", choices: ["膝", "手", "胸", "机"], answer: "膝", weight: 10, explanation: "膝を打つ。" },
  { id: "ver-49", category: "verbal", question: "「（ ）を煮やす」腹を立てる。", choices: ["業", "腹", "釜", "頭"], answer: "業", weight: 15, explanation: "業を煮やす。" },
  { id: "ver-50", category: "verbal", question: "「人口に（ ）」有名になる。", choices: ["膾炙する", "伝承する", "浸透する", "流布する"], answer: "膾炙する", weight: 25, explanation: "広くもてはやされる。" },

  // --- 4. 空間把握 (Spatial: 50問) ---
  { id: "spa-1", category: "spatial", question: "サイコロ。1の裏が6。展開図で1の隣にこれないのは？", choices: ["2", "3", "5", "6"], answer: "6", weight: 5, explanation: "裏面（対面）は隣接できません。" },
  { id: "spa-2", category: "spatial", question: "投影図：正面から見て正方形、上から見て円。この立体は？", choices: ["立方体", "円柱", "球", "円錐"], answer: "円柱", weight: 10, explanation: "横から四角、上から丸は円柱。" },
  { id: "spa-3", category: "spatial", question: "紙を2回折り、角を1箇所切って開く。穴はいくつ？", choices: ["1", "2", "4", "0"], answer: "4", weight: 15, explanation: "4層重なっています。" },
  { id: "spa-4", category: "spatial", question: "一辺3cmの立方体。表面を塗り、一辺1cmに切る。無色の小立方体はいくつ？", choices: ["0", "1", "8", "27"], answer: "1", weight: 18, explanation: "中心の 1*1*1 のみ色がつきません。" },
  { id: "spa-5", category: "spatial", question: "鏡に映った時計が8時20分。実際の時間は？", choices: ["3時40分", "4時40分", "3時20分", "8時40分"], answer: "3時40分", weight: 20, explanation: "12時を軸に反転。" },
  { id: "spa-6", category: "spatial", question: "サッカーボールの五角形の面の数は？", choices: ["10", "12", "20", "32"], answer: "12", weight: 25, explanation: "切頂二十面体は12個の五角形を持ちます。" },
  { id: "spa-7", category: "spatial", question: "立方体の辺の数は全部で？", choices: ["6", "8", "12", "16"], answer: "12", weight: 5, explanation: "上4、下4、縦4。" },
  { id: "spa-8", category: "spatial", question: "球をどこで切っても、断面は必ず？", choices: ["円", "球", "楕円", "半円"], answer: "円", weight: 5, explanation: "球体の断面は円。" },
  { id: "spa-9", category: "spatial", question: "正六面体の展開図は何パターン？", choices: ["6", "9", "11", "13"], answer: "11", weight: 22, explanation: "重複を除くと11パターン。" },
  { id: "spa-10", category: "spatial", 
    question: "このL字図形を「右（時計回り）に90度」回したものはどれ？", 
    choices: ["形状A", "形状B", "形状C", "形状D"], 
    choiceSvgs: [
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><path d="M30,30 L30,70 L70,70" stroke="#6366f1" stroke-width="8" fill="none"/></svg>`,
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><path d="M30,70 L30,30 L70,30" stroke="#6366f1" stroke-width="8" fill="none"/></svg>`,
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><path d="M70,70 L70,30 L30,30" stroke="#6366f1" stroke-width="8" fill="none"/></svg>`,
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><path d="M70,30 L70,70 L30,70" stroke="#6366f1" stroke-width="8" fill="none"/></svg>`
    ],
    answer: "形状B", weight: 10, explanation: "90度回転させると、縦棒が上を向き、横棒が右に伸びる形になります。", 
    svgData: `<svg viewBox="0 0 100 100" class="w-32 h-32 mx-auto"><path d="M30,30 L30,70 L70,70" stroke="#6366f1" stroke-width="8" fill="none"/></svg>` 
  },
  { id: "spa-11", category: "spatial", question: "立方体の頂点の数は？", choices: ["4", "6", "8", "12"], answer: "8", weight: 5, explanation: "上4、下4。" },
  { id: "spa-12", category: "spatial", question: "円錐を真横に切った断面は？", choices: ["円", "楕円", "三角形", "台形"], answer: "円", weight: 8, explanation: "底面に平行な断面。" },
  { id: "spa-13", category: "spatial", question: "正方形の対角線の長さは一辺の何倍？", choices: ["1.2", "1.41", "1.73", "2"], answer: "1.41", weight: 12, explanation: "√2 倍。" },
  { id: "spa-14", category: "spatial", question: "展開図を組み立てた時、1つの点に集まる面数は？（立方体）", choices: ["2", "3", "4", "5"], answer: "3", weight: 15, explanation: "頂点には3面が集まる。" },
  { id: "spa-15", category: "spatial", question: "一辺aの立方体。表面積は？", choices: ["a^2", "4a^2", "6a^2", "a^3"], answer: "6a^2", weight: 10, explanation: "6つの面。" },
  { id: "spa-16", category: "spatial", 
    question: "この形を左右反転（鏡像）させたものはどれ？", 
    choices: ["形状A", "形状B", "形状C", "形状D"], 
    choiceSvgs: [
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><path d="M70,20 L30,50 L70,80 Z" fill="#6366f1" /></svg>`,
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><path d="M30,20 L70,50 L30,80 Z" fill="#6366f1" /></svg>`,
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><path d="M30,80 L70,50 L30,20 Z" fill="#f43f5e" /></svg>`,
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><path d="M50,10 L90,50 L50,90 Z" fill="#6366f1" /></svg>`
    ],
    answer: "形状A", weight: 8, explanation: "左右が入れ替わり、鋭角が左を向く形になります。", 
    svgData: `<svg viewBox="0 0 100 100" class="w-32 h-32 mx-auto"><path d="M30,20 L70,50 L30,80 Z" fill="#6366f1" /></svg>` 
  },
  { id: "spa-17", category: "spatial", question: "球の表面積の公式は？", choices: ["4πr^2", "4/3πr^3", "2πr", "πr^2"], answer: "4πr^2", weight: 15, explanation: "心配ある。" },
  { id: "spa-18", category: "spatial", question: "立方体を1つの平面で切る。五角形の断面は作れるか？", choices: ["できる", "できない", "条件による", "正五角形なら可"], answer: "できる", weight: 25, explanation: "適切に切れば五角形や六角形も可。" },
  { id: "spa-19", category: "spatial", question: "円柱の側面を展開すると？", choices: ["円", "扇形", "長方形", "台形"], answer: "長方形", weight: 5, explanation: "高さ×円周。" },
  { id: "spa-20", category: "spatial", question: "正四面体の辺の数は？", choices: ["4", "6", "8", "12"], answer: "6", weight: 12, explanation: "底面3、側面3。" },
  { id: "spa-21", category: "spatial", 
    question: "この矢印を180度回転させたものはどれ？", 
    choices: ["形状A", "形状B", "形状C", "形状D"], 
    choiceSvgs: [
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><path d="M50,80 L50,20 M30,40 L50,20 L70,40" stroke="#6366f1" stroke-width="8" fill="none"/></svg>`,
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><path d="M20,50 L80,50 M40,30 L20,50 L40,70" stroke="#6366f1" stroke-width="8" fill="none"/></svg>`,
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><path d="M80,50 L20,50 M60,30 L80,50 L60,70" stroke="#6366f1" stroke-width="8" fill="none"/></svg>`,
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><path d="M50,20 L50,80 M30,60 L50,80 L70,60" stroke="#6366f1" stroke-width="8" fill="none"/></svg>`
    ],
    answer: "形状D", weight: 10, explanation: "180度回転は上下左右が完全に入れ替わります。", 
    svgData: `<svg viewBox="0 0 100 100" class="w-32 h-32 mx-auto"><path d="M50,20 L50,80 M30,40 L50,20 L70,40" stroke="#6366f1" stroke-width="8" fill="none"/></svg>` 
  },
  { id: "spa-22", category: "spatial", question: "正三角形だけで作れない正多面体は？", choices: ["正四面体", "正六面体", "正八面体", "正二十面体"], answer: "正六面体", weight: 15, explanation: "正六面体は正方形。" },
  { id: "spa-23", category: "spatial", question: "立方体の対角線は内部に何本？", choices: ["2", "4", "6", "12"], answer: "4", weight: 20, explanation: "頂点ペアを通るもの。" },
  { id: "spa-24", category: "spatial", question: "黄金比の長方形。半分に切ってまた同じ比になるか？", choices: ["なる", "ならない", "条件による", "判定不能"], answer: "ならない", weight: 20, explanation: "正方形を切り取ると黄金比の長方形が残りますが、半分ではありません。" },
  { id: "spa-25", category: "spatial", question: "鏡に映った「TOMATO」。どう見える？", choices: ["そのまま", "OTAMOT", "上下反転", "一部反転"], answer: "OTAMOT", weight: 12, explanation: "左右対称の文字群ですが並びが反転。" },
  { id: "spa-26", category: "spatial", question: "三角形の板を底辺を軸に一回転。形は？", choices: ["円柱", "円錐", "球", "二つの円錐の合体"], answer: "二つの円錐の合体", weight: 15, explanation: "上下対称な円錐。" },
  { id: "spa-27", category: "spatial", question: "立方体の向かい合う面を同色に。最低何色？", choices: ["2", "3", "4", "6"], answer: "3", weight: 10, explanation: "3ペアあるため。" },
  { id: "spa-28", category: "spatial", question: "正三角形の内角は？", choices: ["45", "60", "90", "120"], answer: "60", weight: 3, explanation: "180/3。" },
  { id: "spa-29", category: "spatial", question: "コンパスだけで描ける最も完璧な図形は？", choices: ["正方形", "三角形", "円", "六角形"], answer: "円", weight: 3, explanation: "定義上。" },
  { id: "spa-30", category: "spatial", 
    question: "この図形（棒が刺さった球）の「真上からの影（投影）」はどれ？", 
    choices: ["形状A", "形状B", "形状C", "形状D"], 
    choiceSvgs: [
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><circle cx="50" cy="50" r="30" fill="#6366f1" /></svg>`,
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><circle cx="50" cy="50" r="30" fill="#6366f1" /><rect x="45" y="20" width="10" height="60" fill="#6366f1" /></svg>`,
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><rect x="20" y="45" width="60" height="10" fill="#6366f1" /></svg>`,
      `<svg viewBox="0 0 100 100" class="w-16 h-16 mx-auto"><circle cx="50" cy="50" r="10" fill="#6366f1" /></svg>`
    ],
    answer: "形状B", weight: 10, explanation: "真上から見ると球は円に、突き抜けた棒は長方形に見えます。", 
    svgData: `<svg viewBox="0 0 100 100" class="w-32 h-32 mx-auto"><circle cx="50" cy="50" r="30" fill="#6366f1" /><rect x="45" y="20" width="10" height="60" fill="#6366f1" /></svg>` 
  },
  { id: "spa-31", category: "spatial", question: "ドーナツ型（トーラス）を1回切って2つの輪にできる？", choices: ["できる", "できない", "条件による", "判定不能"], answer: "できない", weight: 25, explanation: "トポロジー的性質。" },
  { id: "spa-32", category: "spatial", question: "立方体を1平面で切る。正三角形の断面は作れる？", choices: ["できる", "できない", "正方形のみ", "条件による"], answer: "できる", weight: 15, explanation: "頂点付近を斜めに切ると可。" },
  { id: "spa-33", category: "spatial", question: "正方形の紙。3回半分に折って角を切る。開くと穴は？", choices: ["4", "8", "16", "1"], answer: "8", weight: 22, explanation: "2^3 = 8層。" },
  { id: "spa-34", category: "spatial", question: "球の中に最大に入る立方体の頂点はどこに接する？", choices: ["中心", "表面", "接しない", "赤道"], answer: "表面", weight: 15, explanation: "内接の定義。" },
  { id: "spa-35", category: "spatial", question: "円錐の展開図。側面は？", choices: ["円", "三角形", "扇形", "半円"], answer: "扇形", weight: 5, explanation: "中心角のある扇形。" },
  { id: "spa-36", category: "spatial", question: "立方体の一辺を半分に。表面積は何分の一？", choices: ["1/2", "1/4", "1/8", "1/16"], answer: "1/4", weight: 12, explanation: "比の2乗。" },
  { id: "spa-37", category: "spatial", question: "直方体。縦2, 横5, 高4。体積は？", choices: ["11", "20", "40", "50"], answer: "40", weight: 5, explanation: "2*5*4。" },
  { id: "spa-38", category: "spatial", question: "正六角形の1つの内角は？", choices: ["60", "100", "120", "150"], answer: "120", weight: 10, explanation: "180*(6-2)/6。" },
  { id: "spa-39", category: "spatial", question: "この迷路を通り抜けられるか？", choices: ["できる", "できない", "一方向のみ", "出口が2つ"], answer: "できる", weight: 8, explanation: "空間把握のテスト。", svgData: `<svg viewBox="0 0 100 100" class="w-32 h-32 mx-auto"><path d="M10,10 H90 V90 H10 Z M30,30 V70 H70 V30 Z" stroke="#6366f1" stroke-width="4" fill="none"/></svg>` },
  { id: "spa-40", category: "spatial", question: "正三角形を組み合わせて作れない正多面体は？", choices: ["正四面体", "正八面体", "正十二面体", "正二十面体"], answer: "正十二面体", weight: 18, explanation: "正十二面体は五角形。" },
  { id: "spa-41", category: "spatial", question: "4次元立方体を3次元に投影。見える立方体数は？", choices: ["4", "6", "8", "12"], answer: "8", weight: 30, explanation: "正八胞体。" },
  { id: "spa-42", category: "spatial", question: "立方体の表面を最短で1周。展開図では？", choices: ["曲線", "折れ線", "直線", "波線"], answer: "直線", weight: 20, explanation: "最短距離の定義。" },
  { id: "spa-43", category: "spatial", question: "球の体積の公式は？", choices: ["4πr^2", "4/3πr^3", "2πr", "πr^2"], answer: "4/3πr^3", weight: 15, explanation: "身の上に心配..." },
  { id: "spa-44", category: "spatial", question: "平行四辺形の面積に不要な情報は？", choices: ["底辺", "高さ", "斜辺", "角度（高さ既知の場合）"], answer: "斜辺", weight: 10, explanation: "底辺×高さ。" },
  { id: "spa-45", category: "spatial", question: "鏡に映った「12時15分」。どう見える？", choices: ["12時45分", "11時45分", "6時15分", "そのまま"], answer: "11時45分", weight: 22, explanation: "時計の反転推察。" },
  { id: "spa-46", category: "spatial", question: "円柱を斜めに切る。断面は？", choices: ["円", "楕円", "長方形", "放物線"], answer: "楕円", weight: 10, explanation: "円柱の斜め切り。" },
  { id: "spa-47", category: "spatial", question: "正方形の対角線で4つに分ける。1つの形は？", choices: ["正三角形", "直角二等辺三角形", "長方形", "菱形"], answer: "直角二等辺三角形", weight: 8, explanation: "対称性より。" },
  { id: "spa-48", category: "spatial", question: "正二十面体の面の形は？", choices: ["正方形", "正三角形", "正五角形", "正六角形"], answer: "正三角形", weight: 15, explanation: "正三角形20枚。" },
  { id: "spa-49", category: "spatial", question: "サッカーボールの六角形の面の数は？", choices: ["12", "20", "32", "10"], answer: "20", weight: 25, explanation: "12個の五角形と20個の六角形。" },
  { id: "spa-50", category: "spatial", question: "立方体を1回切る。六角形の断面は作れる？", choices: ["できる", "できない", "五角形まで", "条件による"], answer: "できる", weight: 30, explanation: "全6面を通るように切ると可。" }
];
