
export interface Question {
  word: string;
  choices: string[];
  answer: string;
}

/**
 * 英単語王 問題バンク (300選)
 * 難易度：中学復習〜難関私大・国公立二次レベル
 */
export const WORD_BANK: Question[] = [
  // --- 動詞 (Verbs) ---
  { word: "abandon", choices: ["捨てる", "蓄える", "禁じる", "達成する"], answer: "捨てる" },
  { word: "accommodate", choices: ["収容する", "計算する", "強調する", "同情する"], answer: "収容する" },
  { word: "acquire", choices: ["習得する", "要求する", "探求する", "質問する"], answer: "習得する" },
  { word: "adjust", choices: ["調整する", "正当化する", "拡大する", "分配する"], answer: "調整する" },
  { word: "advocate", choices: ["主張する", "後退する", "交渉する", "洗練する"], answer: "主張する" },
  { word: "anticipate", choices: ["予想する", "参加する", "後悔する", "区別する"], answer: "予想する" },
  { word: "appreciate", choices: ["正しく評価する", "接近する", "非難する", "承認する"], answer: "正しく評価する" },
  { word: "approximate", choices: ["近い", "適切な", "正確な", "明白な"], answer: "近い" },
  { word: "assemble", choices: ["組み立てる", "驚かせる", "仮定する", "割り当てる"], answer: "組み立てる" },
  { word: "attain", choices: ["達成する", "攻撃する", "試みる", "惹きつける"], answer: "達成する" },
  { word: "betray", choices: ["裏切る", "信じる", "利益を得る", "描写する"], answer: "裏切る" },
  { word: "cherish", choices: ["大切にする", "確認する", "整理する", "破壊する"], answer: "大切にする" },
  { word: "circulate", choices: ["循環する", "模倣する", "祝う", "命令する"], answer: "循環する" },
  { word: "coincide", choices: ["同時に起こる", "協力する", "対立する", "接続する"], answer: "同時に起こる" },
  { word: "commute", choices: ["通勤する", "会話する", "比較する", "計算する"], answer: "通勤する" },
  { word: "compromise", choices: ["妥協する", "構成する", "約束する", "対決する"], answer: "妥協する" },
  { word: "confront", choices: ["直面する", "確認する", "混乱させる", "納得させる"], answer: "直面する" },
  { word: "contradict", choices: ["矛盾する", "予測する", "制限する", "指示する"], answer: "矛盾する" },
  { word: "cultivate", choices: ["耕す・養う", "収穫する", "建設する", "計算する"], answer: "耕す・養う" },
  { word: "demolish", choices: ["取り壊す", "実演する", "描写する", "定義する"], answer: "取り壊す" },
  { word: "deprive", choices: ["奪う", "派生する", "宣言する", "配達する"], answer: "奪う" },
  { word: "derive", choices: ["由来する", "奪う", "決定する", "軽蔑する"], answer: "由来する" },
  { word: "deteriorate", choices: ["悪化する", "決意する", "装飾する", "逸脱する"], answer: "悪化する" },
  { word: "devise", choices: ["考案する", "分割する", "捧げる", "逸脱する"], answer: "考案する" },
  { word: "diminish", choices: ["減らす", "区別する", "定義する", "表示する"], answer: "減らす" },
  { word: "discard", choices: ["捨てる", "発見する", "表示する", "議論する"], answer: "捨てる" },
  { word: "disguise", choices: ["変装させる", "不快にさせる", "解雇する", "分布させる"], answer: "変装させる" },
  { word: "dominate", choices: ["支配する", "寄付する", "装飾する", "描写する"], answer: "支配する" },
  { word: "elaborate", choices: ["詳しく説明する", "除去する", "評価する", "解放する"], answer: "詳しく説明する" },
  { word: "embrace", choices: ["抱きしめる・受け入れる", "恥ずかしくさせる", "強調する", "雇用する"], answer: "抱きしめる・受け入れる" },
  { word: "encounter", choices: ["遭遇する", "勇気づける", "保証する", "同封する"], answer: "遭遇する" },
  { word: "endure", choices: ["耐える", "保証する", "拡大する", "楽しむ"], answer: "耐える" },
  { word: "enforce", choices: ["施行する", "強制する", "同封する", "楽しませる"], answer: "施行する" },
  { word: "enhance", choices: ["高める", "拡大する", "耐える", "囲む"], answer: "高める" },
  { word: "evaluate", choices: ["評価する", "蒸発する", "逸脱する", "進歩する"], answer: "評価する" },
  { word: "exhibit", choices: ["展示する", "展示される", "禁止する", "居住する"], answer: "展示する" },
  { word: "facilitate", choices: ["促進する", "魅了する", "躊躇する", "模倣する"], answer: "促進する" },
  { word: "flourish", choices: ["繁栄する", "磨く", "罰する", "出版する"], answer: "繁栄する" },
  { word: "frustrate", choices: ["挫折させる", "感謝する", "魅了する", "許す"], answer: "挫折させる" },
  { word: "guarantee", choices: ["保証する", "卒業する", "集める", "磨く"], answer: "保証する" },
  { word: "hesitate", choices: ["ためらう", "継承する", "居住する", "阻害する"], answer: "ためらう" },
  { word: "identify", choices: ["特定する", "理想化する", "無視する", "照らす"], answer: "特定する" },
  { word: "illustrate", choices: ["説明する", "照らす", "幻想を抱く", "模倣する"], answer: "説明する" },
  { word: "implement", choices: ["実行する", "暗示する", "押し付ける", "輸入する"], answer: "実行する" },
  { word: "imply", choices: ["暗に示す", "押し付ける", "改善する", "輸入する"], answer: "暗に示す" },
  { word: "indicate", choices: ["示す", "誘導する", "耽溺する", "推論する"], answer: "示す" },
  { word: "inherit", choices: ["相続する", "居住する", "阻害する", "開始する"], answer: "相続する" },
  { word: "inspect", choices: ["検査する", "尊敬する", "期待する", "側面"], answer: "検査する" },
  { word: "install", choices: ["設置する", "侮辱する", "知能", "意図する"], answer: "設置する" },
  { word: "interfere", choices: ["干渉する", "解釈する", "導入する", "調査する"], answer: "干渉する" },
  { word: "interpret", choices: ["解釈する", "干渉する", "中断する", "紹介する"], answer: "解釈する" },
  { word: "intimidate", choices: ["威嚇する", "模倣する", "示す", "開始する"], answer: "威嚇する" },
  { word: "invade", choices: ["侵略する", "発明する", "投資する", "招待する"], answer: "侵略する" },
  { word: "justify", choices: ["正当化する", "判断する", "参加する", "冗談を言う"], answer: "正当化する" },
  { word: "liberate", choices: ["解放する", "制限する", "文字通り", "自由な"], answer: "解放する" },
  { word: "maintain", choices: ["維持する", "管理する", "製造する", "言及する"], answer: "維持する" },
  { word: "manipulate", choices: ["操る", "製造する", "維持する", "管理する"], answer: "操る" },
  { word: "modify", choices: ["修正する", "増幅する", "通知する", "正当化する"], answer: "修正する" },
  { word: "negotiate", choices: ["交渉する", "否定する", "無視する", "通知する"], answer: "交渉する" },
  { word: "notify", choices: ["通知する", "交渉する", "否定する", "無視する"], answer: "通知する" },
  { word: "oblige", choices: ["義務付ける", "反対する", "観察する", "得る"], answer: "義務付ける" },
  { word: "obstacle", choices: ["障害物", "目的", "反対", "観察"], answer: "障害物" },
  { word: "occupy", choices: ["占める", "起こる", "提供する", "反対する"], answer: "占める" },
  { word: "orient", choices: ["適応させる", "注文する", "組織する", "起源"], answer: "適応させる" },
  { word: "overcome", choices: ["打ち勝つ", "見渡す", "追い越す", "過労"], answer: "打ち勝つ" },
  { word: "participate", choices: ["参加する", "分離する", "部分的な", "特に"], answer: "参加する" },
  { word: "perceive", choices: ["知覚する", "説得する", "実行する", "許可する"], answer: "知覚する" },
  { word: "persist", choices: ["固執する", "説得する", "許す", "知覚する"], answer: "固執する" },
  { word: "persuade", choices: ["説得する", "追求する", "知覚する", "固執する"], answer: "説得する" },
  { word: "predict", choices: ["予測する", "防ぐ", "保存する", "ふりをする"], answer: "予測する" },
  { word: "preserve", choices: ["保存する", "予測する", "防ぐ", "ふりをする"], answer: "保存する" },
  { word: "promote", choices: ["促進する", "約束する", "提供する", "保護する"], answer: "促進する" },
  { word: "pursue", choices: ["追求する", "説得する", "購入する", "押す"], answer: "追求する" },
  { word: "reconcile", choices: ["和解させる", "認識する", "推薦する", "回復する"], answer: "和解させる" },
  { word: "refine", choices: ["精製する・洗練する", "拒否する", "反映する", "改革する"], answer: "精製する・洗練する" },
  { word: "regulate", choices: ["規制する", "登録する", "拒否する", "リラックスする"], answer: "規制する" },
  { word: "reinforce", choices: ["強化する", "反映する", "改革する", "拒絶する"], answer: "強化する" },
  { word: "relieve", choices: ["和らげる", "信じる", "解放する", "残る"], answer: "和らげる" },
  { word: "reluctant", choices: ["気が進まない", "信頼できる", "関連のある", "リラックスした"], answer: "気が進まない" },
  { word: "reproduce", choices: ["繁殖する・再現する", "紹介する", "減らす", "交換する"], answer: "繁殖する・再現する" },
  { word: "resemble", choices: ["似ている", "組み立てる", "思い出す", "解決する"], answer: "似ている" },
  { word: "resolve", choices: ["解決する", "予約する", "似ている", "尊敬する"], answer: "解決する" },
  { word: "reveal", choices: ["明らかにする", "復讐する", "回転する", "尊敬する"], answer: "明らかにする" },
  { word: "revise", choices: ["修正する", "復活する", "明らかにする", "尊敬する"], answer: "修正する" },
  { word: "sacrifice", choices: ["犠牲にする", "満足させる", "節約する", "叫ぶ"], answer: "犠牲にする" },
  { word: "speculate", choices: ["推測する", "専門にする", "期待する", "話す"], answer: "推測する" },
  { word: "stimulate", choices: ["刺激する", "シミュレートする", "蓄積する", "似ている"], answer: "刺激する" },
  { word: "substitute", choices: ["代用する", "提出する", "購読する", "引く"], answer: "代用する" },
  { word: "surrender", choices: ["降伏する", "囲む", "生き残る", "調査する"], answer: "降伏する" },
  { word: "suspend", choices: ["吊るす・一時停止する", "疑う", "支える", "供給する"], answer: "吊るす・一時停止する" },
  { word: "sustain", choices: ["維持する", "疑う", "吊るす", "支える"], answer: "維持する" },
  { word: "transform", choices: ["変形させる", "翻訳する", "輸送する", "送信する"], answer: "変形させる" },
  { word: "transmit", choices: ["送信する", "輸送する", "翻訳する", "変形させる"], answer: "送信する" },
  { word: "undergo", choices: ["経験する", "引き受ける", "理解する", "下にある"], answer: "経験する" },
  { word: "utilize", choices: ["利用する", "団結する", "普遍的な", "便利な"], answer: "利用する" },
  { word: "vanish", choices: ["消える", "追放する", "磨く", "罰する"], answer: "消える" },
  { word: "violate", choices: ["違反する", "暴力的な", "価値のある", "変化する"], answer: "違反する" },
  { word: "withdraw", choices: ["撤退する・引き出す", "耐える", "目撃する", "差し控える"], answer: "撤退する・引き出す" },
  { word: "withhold", choices: ["差し控える", "撤退する", "耐える", "目撃する"], answer: "差し控える" },
  { word: "witness", choices: ["目撃する", "耐える", "引き出す", "差し控える"], answer: "目撃する" },

  // --- 形容詞 (Adjectives) ---
  { word: "abundant", choices: ["豊富な", "抽象的な", "絶対的な", "不合理な"], answer: "豊富な" },
  { word: "accurate", choices: ["正確な", "適切な", "積極的な", "切実な"], answer: "正確な" },
  { word: "adjacent", choices: ["隣接した", "適切な", "積極的な", "正確な"], answer: "隣接した" },
  { word: "aesthetic", choices: ["美的な", "運動の", "倫理的な", "大西洋の"], answer: "美的な" },
  { word: "ambiguous", choices: ["あいまいな", "野心的な", "両利きの", "古代の"], answer: "あいまいな" },
  { word: "anonymous", choices: ["匿名の", "膨大な", "満場一致の", "自律的な"], answer: "匿名の" },
  { word: "appropriate", choices: ["適切な", "正確な", "承認された", "概算の"], answer: "適切な" },
  { word: "artificial", choices: ["人工的な", "芸術的な", "巧みな", "正確な"], answer: "人工的な" },
  { word: "authentic", choices: ["本物の", "権威ある", "自動の", "熱心な"], answer: "本物の" },
  { word: "benevolent", choices: ["慈悲深い", "有益な", "穏やかな", "背後の"], answer: "慈悲深い" },
  { word: "brilliant", choices: ["輝かしい", "勇敢な", "簡潔な", "残酷な"], answer: "輝かしい" },
  { word: "capable", choices: ["能力がある", "容量がある", "慎重な", "快適な"], answer: "能力がある" },
  { word: "chronic", choices: ["慢性の", "年代順の", "重大な", "残酷な"], answer: "慢性の" },
  { word: "cognitive", choices: ["認知の", "協力的な", "一貫した", "集団の"], answer: "認知の" },
  { word: "coherent", choices: ["首尾一貫した", "協力的な", "認知の", "集団の"], answer: "首尾一貫した" },
  { word: "comparable", choices: ["比較できる", "快適な", "互換性のある", "競争力のある"], answer: "比較できる" },
  { word: "compatible", choices: ["互換性のある", "比較できる", "快適な", "競争力のある"], answer: "互換性のある" },
  { word: "comprehensive", choices: ["包括的な", "理解できる", "圧縮された", "複雑な"], answer: "包括的な" },
  { word: "compulsory", choices: ["強制的な", "複雑な", "包括的な", "簡潔な"], answer: "強制的な" },
  { word: "confidential", choices: ["機密の", "自信のある", "確信している", "紛らわしい"], answer: "機密 of " },
  { word: "conspicuous", choices: ["目立つ", "意識的な", "連続した", "保守的な"], answer: "目立つ" },
  { word: "contemporary", choices: ["現代の", "一時的な", "軽蔑的な", "満足した"], answer: "現代の" },
  { word: "crucial", choices: ["重大な", "残酷な", "粗末な", "好奇心旺盛な"], answer: "重大な" },
  { word: "decisive", choices: ["決定的な", "欺瞞的な", "欠陥のある", "繊細な"], answer: "決定的な" },
  { word: "deliberate", choices: ["意図的な", "繊細な", "おいしい", "喜ばしい"], answer: "意図的な" },
  { word: "desperate", choices: ["絶望的な・必死の", "分離した", "不快な", "望ましい"], answer: "絶望的な・必死の" },
  { word: "diverse", choices: ["多様な", "逆の", "異なる", "分割された"], answer: "多様な" },
  { word: "drastic", choices: ["徹底的な", "劇的な", "乾燥した", "夢のような"], answer: "徹底的な" },
  { word: "efficient", choices: ["効率的な", "十分な", "効果的な", "顕著な"], answer: "効率的な" },
  { word: "elaborate", choices: ["精巧な", "複雑な", "適切な", "明白な"], answer: "精巧な" },
  { word: "elegant", choices: ["優雅な", "適切な", "積極的な", "切実な"], answer: "優雅な" },
  { word: "eminent", choices: ["著名な", "差し迫った", "広大な", "空の"], answer: "著名な" },
  { word: "empirical", choices: ["経験的な", "帝国の", "空の", "熱心な"], answer: "経験的な" },
  { word: "equivalent", choices: ["同等の", "等しい", "装備された", "不可欠な"], answer: "同等の" },
  { word: "essential", choices: ["不可欠な", "同等の", "等しい", "装備された"], answer: "不可欠な" },
  { word: "exclusive", choices: ["独占的な", "排他的な", "高価な", "過度な"], answer: "独占的な" },
  { word: "explicit", choices: ["明白な", "暗黙の", "複雑な", "外部の"], answer: "明白な" },
  { word: "feasible", choices: ["実行可能な", "恐ろしい", "柔軟な", "はかない"], answer: "実行可能な" },
  { word: "flexible", choices: ["柔軟な", "恐ろしい", "実行可能な", "はかない"], answer: "柔軟な" },
  { word: "fragile", choices: ["壊れやすい", "実用的な", "はかない", "柔軟な"], answer: "壊れやすい" },
  { word: "genuine", choices: ["本物の", "一般的な", "寛大な", "優しい"], answer: "本物の" },
  { word: "hostile", choices: ["敵対的な", "謙虚な", "湿った", "巨大な"], answer: "敵対的な" },
  { word: "humble", choices: ["謙虚な", "敵対的な", "湿った", "巨大な"], answer: "謙虚な" },
  { word: "identical", choices: ["同一の", "理想的な", "特有の", "不活発な"], answer: "同一の" },
  { word: "ignorant", choices: ["無知な", "無視された", "照らされた", "不法な"], answer: "無知な" },
  { word: "immense", choices: ["巨大な", "差し迫った", "免疫の", "不道徳な"], answer: "巨大な" },
  { word: "imminent", choices: ["差し迫った", "巨大な", "免疫の", "不道徳な"], answer: "差し迫った" },
  { word: "implicit", choices: ["暗黙の", "明白な", "複雑な", "外部の"], answer: "暗黙の" },
  { word: "incredible", choices: ["信じられない", "避けられない", "不可欠な", "不治の"], answer: "信じられない" },
  { word: "indispensable", choices: ["不可欠な", "信じられない", "避けられない", "不治の"], answer: "不可欠な" },
  { word: "inevitable", choices: ["避けられない", "不可欠な", "信じられない", "不治の"], answer: "避けられない" },
  { word: "infinite", choices: ["無限の", "不特定な", "不適切な", "固有の"], answer: "無限の" },
  { word: "inherent", choices: ["固有の", "無限の", "不特定な", "不適切な"], answer: "固有の" },
  { word: "innate", choices: ["生まれつきの", "無害な", "革新的な", "不十分な"], answer: "生まれつきの" },
  { word: "intact", choices: ["無傷の", "内部の", "知的な", "強烈な"], answer: "無傷の" },
  { word: "intense", choices: ["強烈な", "知的な", "内部の", "無傷の"], answer: "強烈な" },
  { word: "internal", choices: ["内部の", "強烈な", "知的な", "無傷の"], answer: "内部の" },
  { word: "intricate", choices: ["複雑な", "興味深い", "内部の", "強烈な"], answer: "複雑な" },
  { word: "irrelevant", choices: ["無関係な", "不合理な", "不規則な", "責任感のない"], answer: "無関係な" },
  { word: "legitimate", choices: ["正当な", "合法的な", "文字通りの", "自由な"], answer: "正当な" },
  { word: "literal", choices: ["文字通りの", "正当な", "合法的な", "自由な"], answer: "文字通りの" },
  { word: "mandatory", choices: ["義務的な", "管理の", "手作業の", "多数の"], answer: "義務的な" },
  { word: "marginal", choices: ["わずかな・限界の", "多数の", "義務的な", "管理の"], answer: "わずかな・限界の" },
  { word: "mutual", choices: ["相互の", "多数の", "わずかな", "義務的な"], answer: "相互の" },
  { word: "naive", choices: ["世間知らずの", "固有の", "固有の", "自然な"], answer: "世間知らずの" },
  { word: "neutral", choices: ["中立の", "自然な", "負の", "普通の"], answer: "中立の" },
  { word: "notable", choices: ["注目すべき", "普通の", "中立の", "負の"], answer: "注目すべき" },
  { word: "obscure", choices: ["不明瞭な", "明らかな", "障害物", "観察"], answer: "不明瞭な" },
  { word: "obsolete", choices: ["廃れた", "明白な", "障害物", "観察"], answer: "廃れた" },
  { word: "optimistic", choices: ["楽観的な", "悲観的な", "最適な", "任意の"], answer: "楽観的な" },
  { word: "optional", choices: ["任意の", "最適な", "楽観的な", "悲観的な"], answer: "任意の" },
  { word: "permanent", choices: ["永続的な", "一時的な", "個人的な", "積極的な"], answer: "永続的な" },
  { word: "pessimistic", choices: ["悲観的な", "楽観的な", "最適な", "任意の"], answer: "悲観的な" },
  { word: "plausible", choices: ["もっともらしい", "可能性のある", "明白な", "貴重な"], answer: "もっともらしい" },
  { word: "precious", choices: ["貴重な", "もっともらしい", "可能性のある", "明白な"], answer: "貴重な" },
  { word: "precise", choices: ["正確な", "貴重な", "もっともらしい", "可能性のある"], answer: "正確な" },
  { word: "prevalent", choices: ["普及している", "正確な", "貴重な", "もっともらしい"], answer: "普及している" },
  { word: "primitive", choices: ["原始的な", "主要な", "普及している", "正確な"], answer: "原始的な" },
  { word: "prominent", choices: ["著名な", "原始的な", "主要な", "普及している"], answer: "著名な" },
  { word: "radical", choices: ["根本的な・急進的な", "放射状の", "まれな", "合理的な"], answer: "根本的な・急進的な" },
  { word: "rational", choices: ["合理的な", "急進的な", "まれな", "根本的な"], answer: "合理的な" },
  { word: "redundant", choices: ["余分な", "最近の", "合理的な", "急進的な"], answer: "余分な" },
  { word: "relevant", choices: ["関連のある", "余分な", "最近の", "合理的な"], answer: "関連のある" },
  { word: "reliable", choices: ["信頼できる", "関連のある", "余分な", "最近の"], answer: "信頼できる" },
  { word: "remarkable", choices: ["注目すべき", "信頼できる", "関連のある", "余分な"], answer: "注目すべき" },
  { word: "rigid", choices: ["硬い・厳格な", "注目すべき", "信頼できる", "関連のある"], answer: "硬い・厳格な" },
  { word: "scarce", choices: ["乏しい", "厳格な", "注目すべき", "信頼できる"], answer: "乏しい" },
  { word: "sensitive", choices: ["敏感な", "乏しい", "厳格な", "注目すべき"], answer: "敏感な" },
  { word: "significant", choices: ["重要な", "敏感な", "乏しい", "厳格な"], answer: "重要な" },
  { word: "simultaneous", choices: ["同時の", "重要な", "敏感な", "乏しい"], answer: "同時の" },
  { word: "skeptical", choices: ["懐疑的な", "同時の", "重要な", "敏感な"], answer: "懐疑的な" },
  { word: "sophisticated", choices: ["洗練された", "懐疑的な", "同時の", "重要な"], answer: "洗練された" },
  { word: "spontaneous", choices: ["自発的な", "洗練された", "懐疑的な", "同時の"], answer: "自発的な" },
  { word: "stable", choices: ["安定した", "自発的な", "洗練された", "懐疑的な"], answer: "安定した" },
  { word: "subtle", choices: ["微妙な", "安定した", "自発的な", "洗練された"], answer: "微妙な" },
  { word: "sufficient", choices: ["十分な", "微妙な", "安定した", "自発的な"], answer: "十分な" },
  { word: "superficial", choices: ["表面的な", "十分な", "微妙な", "安定した"], answer: "表面的な" },
  { word: "tangible", choices: ["具体的な・有形の", "表面的な", "十分な", "微妙な"], answer: "具体的な・有形の" },
  { word: "temporary", choices: ["一時的な", "具体的な", "表面的な", "十分な"], answer: "一時的な" },
  { word: "trivial", choices: ["些細な", "一時的な", "具体的な", "表面的な"], answer: "些細な" },
  { word: "unanimous", choices: ["満場一致の", "些細な", "一時的な", "具体的な"], answer: "満場一致の" },
  { word: "vague", choices: ["あいまいな", "満場一致の", "些細な", "一時的な"], answer: "あいまいな" },
  { word: "valid", choices: ["有効な", "あいまいな", "満場一致の", "些細な"], answer: "有効な" },
  { word: "variable", choices: ["変わりやすい", "有効な", "あいまいな", "満場一致の"], answer: "変わりやすい" },
  { word: "versatile", choices: ["多才な", "変わりやすい", "有効な", "あいまいな"], answer: "多才な" },
  { word: "vulnerable", choices: ["脆弱な", "多才な", "変わりやすい", "有効な"], answer: "脆弱な" },

  // --- 名詞 (Nouns) ---
  { word: "abundance", choices: ["豊富", "欠乏", "抽象", "絶対"], answer: "豊富" },
  { word: "advocacy", choices: ["擁護・主張", "反対", "協力", "交渉"], answer: "擁護・主張" },
  { word: "affluence", choices: ["裕福", "影響", "努力", "重要"], answer: "裕福" },
  { word: "agony", choices: ["苦痛", "喜び", "合意", "農業"], answer: "苦痛" },
  { word: "ambiguity", choices: ["あいまいさ", "明白さ", "野心", "古代"], answer: "あいまいさ" },
  { word: "analogy", choices: ["類推", "分析", "解剖", "祖先"], answer: "類推" },
  { word: "ancestor", choices: ["先祖", "類推", "分析", "解剖"], answer: "先祖" },
  { word: "anguish", choices: ["苦悩", "喜び", "合意", "農業"], answer: "苦悩" },
  { word: "apparatus", choices: ["装置", "外見", "アピール", "食欲"], answer: "装置" },
  { word: "artifact", choices: ["工芸品", "人工", "記事", "芸術家"], answer: "工芸品" },
  { word: "aspiration", choices: ["熱望", "吸入", "側面", "暗殺"], answer: "熱望" },
  { word: "autonomy", choices: ["自律", "自動", "権威", "自動車"], answer: "自律" },
  { word: "benevolence", choices: ["慈悲", "有益", "穏やか", "背後"], answer: "慈悲" },
  { word: "boundary", choices: ["境界", "跳躍", "束", "バウンティ"], answer: "境界" },
  { word: "chaos", choices: ["混乱", "秩序", "性格", "慈善"], answer: "混乱" },
  { word: "civilization", choices: ["文明", "市民", "都市", "文化"], answer: "文明" },
  { word: "cohesion", choices: ["結合", "一貫", "協力", "認知"], answer: "結合" },
  { word: "commodity", choices: ["商品", "快適", "通勤", "委員会"], answer: "商品" },
  { word: "compassion", choices: ["同情", "情熱", "比較", "仲間"], answer: "同情" },
  { word: "complexity", choices: ["複雑さ", "完成", "不満", "お世辞"], answer: "複雑さ" },
  { word: "compliance", choices: ["遵守", "複雑さ", "完成", "不満"], answer: "遵守" },
  { word: "compromise", choices: ["妥協", "約束", "構成", "対決"], answer: "妥協" },
  { word: "concession", choices: ["譲歩", "概念", "結論", "会議"], answer: "譲歩" },
  { word: "conflict", choices: ["衝突", "自信", "混乱", "確認"], answer: "衝突" },
  { word: "conformity", choices: ["順応", "確認", "会議", "信頼"], answer: "順応" },
  { word: "consensus", choices: ["同意", "感覚", "良心", "結果"], answer: "同意" },
  { word: "consequence", choices: ["結果", "同意", "感覚", "良心"], answer: "結果" },
  { word: "controversy", choices: ["論争", "契約", "対照", "貢献"], answer: "論争" },
  { word: "convention", choices: ["慣習", "便利", "会話", "転換"], answer: "慣習" },
  { word: "criterion", choices: ["基準", "批評", "危機", "作物"], answer: "基準" },
  { word: "curiosity", choices: ["好奇心", "治療", "通貨", "現在"], answer: "好奇心" },
  { word: "deception", choices: ["欺瞞", "決定", "減少", "宣言"], answer: "欺瞞" },
  { word: "deficit", choices: ["赤字", "欠陥", "定義", "度"], answer: "赤字" },
  { word: "demographics", choices: ["人口統計", "民主主義", "実演", "記述"], answer: "人口統計" },
  { word: "departure", choices: ["出発", "依存", "描写", "預金"], answer: "出発" },
  { word: "dignity", choices: ["尊厳", "デジタル", "夕食", "方向"], answer: "尊厳" },
  { word: "disaster", choices: ["災害", "病気", "距離", "分布"], answer: "災害" },
  { word: "diversity", choices: ["多様性", "逆境", "離婚", "分配"], answer: "多様性" },
  { word: "ecology", choices: ["生態学", "経済", "教育", "努力"], answer: "生態学" },
  { word: "efficiency", choices: ["効率", "十分", "効果", "顕著"], answer: "効率" },
  { word: "equilibrium", choices: ["均衡", "装備", "等価", "必須"], answer: "均衡" },
  { word: "evolution", choices: ["進化", "証拠", "評価", "逸脱"], answer: "進化" },
  { word: "fabrication", choices: ["捏造", "工場", "布地", "才能"], answer: "捏造" },
  { word: "fluctuation", choices: ["変動", "流暢", "流体", "飛行"], answer: "変動" },
  { word: "fragment", choices: ["破片", "香り", "枠組み", "頻度"], answer: "破片" },
  { word: "friction", choices: ["摩擦", "虚構", "分画", "断片"], answer: "摩擦" },
  { word: "garment", choices: ["衣服", "庭", "保証", "ゴミ"], answer: "衣服" },
  { word: "gravity", choices: ["重力", "墓", "感謝", "恵み"], answer: "重力" },
  { word: "hierarchy", choices: ["階級制度", "高い", "隠す", "ハイキング"], answer: "階級制度" },
  { word: "hostility", choices: ["敵意", "謙虚", "湿気", "巨大"], answer: "敵意" },
  { word: "hypothesis", choices: ["仮説", "結論", "分析", "観察"], answer: "仮説" },
  { word: "illusion", choices: ["幻想", "説明", "照らす", "模倣"], answer: "幻想" },
  { word: "incentive", choices: ["動機・励み", "入射", "知性", "意図"], answer: "動機・励み" },
  { word: "infrastructure", choices: ["社会基盤", "影響", "構造", "情報"], answer: "社会基盤" },
  { word: "innovation", choices: ["革新", "無実", "入力", "洞察"], answer: "革新" },
  { word: "insight", choices: ["洞察", "革新", "無実", "入力"], answer: "洞察" },
  { word: "integrity", choices: ["誠実・整合性", "知性", "強烈", "関心"], answer: "誠実・整合性" },
  { word: "interference", choices: ["干渉", "解釈", "導入", "調査"], answer: "干渉" },
  { word: "isolation", choices: ["孤立", "島", "問題", "側面"], answer: "孤立" },
  { word: "jurisdiction", choices: ["管轄権", "陪審", "正義", "ジャーナリズム"], answer: "管轄権" },
  { word: "kinship", choices: ["親族関係", "親切", "王権", "知識"], answer: "親族関係" },
  { word: "landscape", choices: ["風景", "土地", "言語", "ランタン"], answer: "風景" },
  { word: "legislation", choices: ["立法", "正当", "文字通り", "自由"], answer: "立法" },
  { word: "magnitude", choices: ["大きさ・重要性", "多数", "手作業", "管理"], answer: "大きさ・重要性" },
  { word: "manifestation", choices: ["現れ", "マニフェスト", "製造", "管理"], answer: "現れ" },
  { word: "notion", choices: ["概念", "注意", "通知", "何もない"], answer: "概念" },
  { word: "nuance", choices: ["微妙な違い", "新しい", "通知", "概念"], answer: "微妙な違い" },
  { word: "objective", choices: ["目的・客観的な", "反対", "観察", "障害物"], answer: "目的・客観的な" },
  { word: "paradigm", choices: ["理論的枠組み", "楽園", "パラドックス", "段落"], answer: "理論的枠組み" },
  { word: "perspective", choices: ["観点・見方", "持続", "繁栄", "熱望"], answer: "観点・見方" },
  { word: "phenomenon", choices: ["現象", "電話", "句", "物理"], answer: "現象" },
  { word: "precedent", choices: ["先例", "大統領", "圧力", "精密"], answer: "先例" },
  { word: "priority", choices: ["優先事項", "以前の", "主要な", "プライバシー"], answer: "優先事項" },
  { word: "propensity", choices: ["傾向", "特性", "繁栄", "熱望"], answer: "傾向" },
  { word: "recession", choices: ["景気後退", "最近", "レセプション", "記録"], answer: "景気後退" },
  { word: "reconciliation", choices: ["和解", "認識", "推薦", "回復"], answer: "和解" },
  { word: "regulation", choices: ["規制", "登録", "拒否", "リラックス"], answer: "規制" },
  { word: "resistance", choices: ["抵抗", "最近", "レセプション", "記録"], answer: "抵抗" },
  { word: "rhetoric", choices: ["修辞学・誇張", "リズム", "権利", "硬い"], answer: "修辞学・誇張" },
  { word: "scrutiny", choices: ["精査", "スクリプト", "彫刻", "海"], answer: "精査" },
  { word: "sovereignty", choices: ["主権", "解決", "源", "南"], answer: "主権" },
  { word: "sustainability", choices: ["持続可能性", "サスペンス", "供給", "支え"], answer: "持続可能性" },
  { word: "synergy", choices: ["相乗効果", "象徴", "同情", "症状"], answer: "相乗効果" },
  { word: "testimony", choices: ["証言", "試験", "教科書", "テクスチャ"], answer: "証言" },
  { word: "trajectory", choices: ["軌道", "悲劇", "伝統", "交通"], answer: "軌道" },
  { word: "transformation", choices: ["変形", "翻訳", "輸送", "送信"], answer: "変形" },
  { word: "validity", choices: ["有効性", "あいまい", "満場一致", "些細"], answer: "有効性" },
  { word: "vulnerability", choices: ["脆弱性", "多才", "変わりやすい", "有効"], answer: "脆弱性" },

  // --- 熟語 (Idioms/Phrases) ---
  { word: "take after", choices: ["似ている", "世話をする", "調査する", "追いかける"], answer: "似ている" },
  { word: "look into", choices: ["調査する", "似ている", "世話をする", "追いかける"], answer: "調査する" },
  { word: "bring about", choices: ["引き起こす", "提出する", "持ち出す", "育てる"], answer: "引き起こす" },
  { word: "carry out", choices: ["実行する", "持ち出す", "育てる", "引き起こす"], answer: "実行する" },
  { word: "set up", choices: ["設置する", "引き起こす", "実行する", "持ち出す"], answer: "設置する" },
  { word: "put off", choices: ["延期する", "脱ぐ", "消す", "耐える"], answer: "延期する" },
  { word: "call off", choices: ["中止する", "延期する", "耐える", "消す"], answer: "中止する" },
  { word: "make up for", choices: ["払い戻す", "埋め合わせをする", "化粧をする", "作り上げる"], answer: "埋め合わせをする" },
  { word: "keep up with", choices: ["遅れずについていく", "我慢する", "連絡を取り合う", "続ける"], answer: "遅れずについていく" },
  { word: "put up with", choices: ["我慢する", "遅れずについていく", "連絡を取り合う", "続ける"], answer: "我慢する" },
  { word: "get along with", choices: ["仲良くやっていく", "我慢する", "遅れずについていく", "続ける"], answer: "仲良くやっていく" },
  { word: "hand in", choices: ["提出する", "配布する", "手渡す", "助ける"], answer: "提出する" },
  { word: "turn down", choices: ["拒絶する", "音を下げる", "倒す", "曲がる"], answer: "拒絶する" },
  { word: "look up to", choices: ["尊敬する", "見上げる", "調べる", "世話をする"], answer: "尊敬する" },
  { word: "look down on", choices: ["軽蔑する", "見下ろす", "調べる", "世話をする"], answer: "軽蔑する" },
  { word: "run out of", choices: ["使い果たす", "走り出す", "逃げる", "追い越す"], answer: "使い果たす" },
  { word: "stand for", choices: ["表す・象徴する", "立つ", "耐える", "支持する"], answer: "表す・象徴する" },
  { word: "take part in", choices: ["参加する", "部分的に", "役割を果たす", "取り分"], answer: "参加する" },
  { word: "account for", choices: ["説明する・占める", "数える", "考慮する", "責任を負う"], answer: "説明する・占める" },
  { word: "depend on", choices: ["依存する", "独立する", "決定する", "防衛する"], answer: "依存する" }
];
